name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed

  $CHANGES

  # Contributors

  $CONTRIBUTORS

  **[Full Changelog](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)**

categories:
  - title: "Breaking"
    label: "breaking"

  - title: "Features"
    labels:
      - "feature"
      - "feat"

  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"
      - "bugfix"

  - title: "Maintenance"
    labels:
      - "chore"
      - "deps"
      - "ci"
      - "security"

  - title: "Documentation"
    label: "docs"

  - title: "Other changes"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "feat"
  patch:
    labels:
      - "fix"
      - "bug"
      - "bugfix"
      - "chor"
      - "docs"
      - "deps"
      - "security"
      - "ci"

exclude-labels:
  - "skip-changelog"
