[stat]
regexp = '^([/\w\.]+\/)?stat\b'
file = 'stat.toml'

[ping]
regexp = '^([/\w\.]+\/)?(io|o|n|h|arp|l2)?ping[236]?\b'
file = 'ping.toml'

[cp]
regexp = '^([/\w\.]+\/)?cp\b'
file = 'cp.toml'

[mv]
regexp = '^([/\w\.]+\/)?mv\b'
file = 'mv.toml'

[rm]
regexp = '^([/\w\.]+\/)?rm\b'
file = 'rm.toml'

[df]
regexp = '^([/\w\.]+\/)?df\b'
file = 'df.toml'

[du]
regexp = '^([/\w\.]+\/)?du\b'
file = 'du.toml'

[lsblk]
regexp = '^([/\w\.]+\/)?lsblk\b'
file = 'lsblk.toml'

[traceroute]
regexp = '^([/\w\.]+\/)?traceroute6?\b'
file = 'traceroute.toml'

[ps]
regexp = '^([/\w\.]+\/)?ps\b'
file = 'ps.toml'

[mount]
regexp = '^([/\w\.]+\/)?mount\b'
file = 'mount.toml'

[env]
regexp = '^([/\w\.]+\/)?env\b'
file = 'env.toml'

[lsmod]
regexp = '^([/\w\.]+\/)?lsmod\b'
file = 'lsmod.toml'

[free]
regexp = '^([/\w\.]+\/)?free\b'
file = 'free.toml'

[docker-version]
regexp = '^(sudo\s)?([/\w\.]+\/)?docker\sversion\b'
file = 'docker-version.toml'

[docker-ps]
regexp = '^(sudo\s)?([/\w\.]+\/)?docker\sps\b'
file = 'docker-ps.toml'

[docker-info]
regexp = '^(sudo\s)?([/\w\.]+\/)?docker\sinfo\b'
file = 'docker-info.toml'
