[stat]
regexp = '^([/\w\.]+\/)?stat'
file = 'stat.toml'

[ping]
regexp = '^([/\w\.]+\/)?(io|o|n|h|arp|l2)?ping[236]?'
file = 'ping.toml'

[df]
regexp = '^([/\w\.]+\/)?df'
file = 'df.toml'

[lsblk]
regexp = '^([/\w\.]+\/)?lsblk\b'
file = 'lsblk.toml'
