[stat]
regexp = '^([/\w\.]+\/)?stat\b'
file = 'stat.toml'

[ping]
regexp = '^([/\w\.]+\/)?(io|o|n|h|arp|l2)?ping[236]?\b'
file = 'ping.toml'

[cp]
regexp = '^([/\w\.]+\/)?cp\b'
file = 'cp.toml'

[mv]
regexp = '^([/\w\.]+\/)?mv\b'
file = 'mv.toml'

[rm]
regexp = '^([/\w\.]+\/)?rm\b'
file = 'rm.toml'

[df]
regexp = '^([/\w\.]+\/)?df\b'
file = 'df.toml'

[du]
regexp = '^([/\w\.]+\/)?du\b'
file = 'du.toml'

[id]
regexp = '^([/\w\.]+\/)?id\b'
file = 'id.toml'

[lsblk]
regexp = '^([/\w\.]+\/)?lsblk\b'
file = 'lsblk.toml'

[traceroute]
regexp = '^([/\w\.]+\/)?traceroute6?\b'
file = 'traceroute.toml'

[ps]
regexp = '^([/\w\.]+\/)?ps\b'
file = 'ps.toml'

[mount]
regexp = '^([/\w\.]+\/)?mount\b'
file = 'mount.toml'

[env]
regexp = '^([/\w\.]+\/)?env\b'
file = 'env.toml'

[lsmod]
regexp = '^([/\w\.]+\/)?lsmod\b'
file = 'lsmod.toml'

[free]
regexp = '^([/\w\.]+\/)?free\b'
file = 'free.toml'

[yt-dlp]
regexp = '^([/\w\.]+\/)?yt-dlp\b'
file = 'yt-dlp.toml'

[docker]
regexp = '^([/\w\.]+\/)?docker\b'
[docker.sub.ps]
regexp = '^([/\w\.]+\/)?docker(\scompose.*)?\sps\b'
file = 'docker-ps.toml'
[docker.sub.version]
regexp = '^([/\w\.]+\/)?docker\sversion\b'
file = 'docker-version.toml'
[docker.sub.info]
regexp = '^([/\w\.]+\/)?docker\sinfo\b'
file = 'docker-info.toml'
[docker.sub.network]
regexp = '^([/\w\.]+\/)?docker\snetwork\b'
file = 'docker-network.toml'
[docker.sub.image]
regexp = '^([/\w\.]+\/)?docker\simage\b'
file = 'docker-image.toml'

[docker-compose]
regexp = '^([/\w\.]+\/)?docker-compose\b'
[docker-compose.sub.ps]
regexp = '^([/\w\.]+\/)?docker-compose\sps\b'
file = 'docker-ps.toml'

[go.sub.test]
regexp = '^([/\w\.]+\/)?go\stest\b'
file = 'go-test.toml'

[strace]
regexp = '^([/\w\.]+\/)?strace\b'
file = 'strace.toml'

[find]
regexp = '^([/\w\.]+\/)?find\b'
file = 'find.toml'

[curl]
regexp = '^([/\w\.]+\/)?curl\b'
file = 'curl.toml'

[wget]
regexp = '^([/\w\.]+\/)?wget\b'
file = 'wget.toml'
