Output demo.gif

Set Theme "Catppuccin Mocha"
Set Shell fish
Set FontSize 40
Set Width    1200
Set Height   1000

Type "# Default find and du command!"
Enter

Type "find ./cmd"
Sleep 500ms
Enter

Sleep 1

Type "du -h ./cmd"
Sleep 500ms
Enter

Sleep 1

Ctrl+L

Type "# Now, using chromashift!"
Enter

Type "cshift alias fish | source"
Sleep 500ms
Enter

Sleep 1

Type "find ./cmd"
Sleep 500ms
Enter

Sleep 1

Type "du -h ./cmd"
Sleep 500ms
Enter

Sleep 3

