package cmd

import "github.com/muesli/termenv"

func GetColorCode(colorName string) string {
	switch colorName {
	case "reset":
		return termenv.ResetSeq
	case "bold":
		return termenv.BoldSeq
	case "underline":
		return termenv.UnderlineSeq
	case "blink":
		return termenv.BlinkSeq
	case "reverse":
		return termenv.ReverseSeq
	case "black":
		return termenv.ANSIBlack.Sequence(false)
	case "red":
		return termenv.ANSIRed.Sequence(false)
	case "green":
		return termenv.ANSIGreen.Sequence(false)
	case "yellow":
		return termenv.ANSIYellow.Sequence(false)
	case "blue":
		return termenv.ANSIBlue.Sequence(false)
	case "magenta":
		return termenv.ANSIMagenta.Sequence(false)
	case "cyan":
		return termenv.ANSICyan.Sequence(false)
	case "white":
		return termenv.ANSIWhite.Sequence(false)
	case "hiblack":
		return termenv.ANSIBrightBlack.Sequence(false)
	case "hired":
		return termenv.ANSIBrightRed.Sequence(false)
	case "higreen":
		return termenv.ANSIBrightGreen.Sequence(false)
	case "hiyellow":
		return termenv.ANSIBrightYellow.Sequence(false)
	case "hiblue":
		return termenv.ANSIBrightBlue.Sequence(false)
	case "himagenta":
		return termenv.ANSIBrightMagenta.Sequence(false)
	case "hicyan":
		return termenv.ANSIBrightCyan.Sequence(false)
	case "hiwhite":
		return termenv.ANSIBrightWhite.Sequence(false)
	case "bgblack":
		return termenv.ANSIBlack.Sequence(true)
	case "bgred":
		return termenv.ANSIRed.Sequence(true)
	case "bggreen":
		return termenv.ANSIGreen.Sequence(true)
	case "bgyellow":
		return termenv.ANSIYellow.Sequence(true)
	case "bgblue":
		return termenv.ANSIBlue.Sequence(true)
	case "bgmagenta":
		return termenv.ANSIMagenta.Sequence(true)
	case "bgcyan":
		return termenv.ANSICyan.Sequence(true)
	case "bgwhite":
		return termenv.ANSIWhite.Sequence(true)
	case "bghiblack":
		return termenv.ANSIBrightBlack.Sequence(true)
	case "bghired":
		return termenv.ANSIBrightRed.Sequence(true)
	case "bghigreen":
		return termenv.ANSIBrightGreen.Sequence(true)
	case "bghiyellow":
		return termenv.ANSIBrightYellow.Sequence(true)
	case "bghiblue":
		return termenv.ANSIBrightBlue.Sequence(true)
	case "bghimagenta":
		return termenv.ANSIBrightMagenta.Sequence(true)
	case "bghicyan":
		return termenv.ANSIBrightCyan.Sequence(true)
	case "bghiwhite":
		return termenv.ANSIBrightWhite.Sequence(true)
	default:
		return ""
	}
}
