"$schema" = "../rule.schema.json"

[FS]
regexp = '^(Filesystem.*)$'
colors = 'bold blue'

[Device]
regexp = '^((\/?[-\w\d.\s]+)+)\s'
colors = 'bold cyan'

[Mounted]
regexp = '(\/$|(\/[-\w\d. ]+)+)$'
colors = 'bold green'

[Size-K-OR-B]
regexp = '(\s\d*[.,]?\d(K|B)i?\s)|\s(\d{1,3}\s)'
colors = 'green'

[Size-M]
regexp = '(\s\d*[.,]?\dMi?\s)|\s(\d{4,6}\s)'
colors = 'yellow'

[Size-G]
regexp = '(\s\d*[.,]?\dGi?\s)|\s(\d{7,9}\s)'
colors = 'red'

[Size-T]
regexp = '(\s\d*[.,]?\dTi?\s)|\s(\d{10,12}\s)'
colors = 'bold red'

[Use_0-60]
regexp = '(\s[1-6]?[0-9]%\s)'
colors = 'green'

[Use_70-89]
regexp = '(\s[78][0-9]%\s)'
colors = 'yellow'

[Use_90-97]
regexp = '(\s9[0-7]%\s)'
colors = 'red'

[Use_98-100]
regexp = '(\s9[89]%|100%\s)'
colors = 'bold red'

[Tmpfs_Lines]
type = 'only'
regexp = '(^tmpfs.*)'
colors = 'black'
