"$schema" = "../rule.schema.json"

[[rules]] # Path
regexp = '\s+((?:[\.\/]+[\w\s\-\_\.]+)(?:\/.*)?)$'
type = 'path'

[[rules]] # Size 'K'
regexp = '^(\d{1,3})\s'
colors = 'green'

[[rules]] # Size 'K'
regexp = '^ ?(\d*[.,]?\dKi?)\s'
colors = 'green'

[[rules]] # Size 'M'
regexp = '^(\d{4,6})\s'
colors = 'yellow'

[[rules]] # Size 'M'
regexp = '^ ?(\d*[.,]?\dMi?)\s'
colors = 'yellow'

[[rules]] # Size 'G'
regexp = '^(\d{7,9})\s'
colors = 'red'

[[rules]] # Size 'G'
regexp = '^ ?(\d*[.,]?\dGi?)\s'
colors = 'red'

[[rules]] # Size 'T'
regexp = '^(\d{10,12})\s'
colors = 'bold red'

[[rules]] # Size 'T'
regexp = '^ ?(\d*[.,]?\dTi?)\s'
colors = 'bold red'

[[rules]] # Total
regexp = '(.*)\s+(total)$'
colors = 'bold yellow bgblue'
