"$schema" = "../rule.schema.json"

[[rules]] # Groups
regexp = '(\d+)\((\w+)\)'
colors = ',yellow,bold yellow'

[[rules]] # User
regexp = 'uid.(\d+)\((\w+)\)'
colors = ',green,bold green'

[[rules]] # SELinux
regexp = '(\w+_u):(\w+_r):(\w+_t):([\w\-.:]+)'
colors = ',green,yellow,cyan,magenta'
