"$schema" = "../rule.schema.json"

[[rules]] # DateTime
regexp = '\s(\w{3})\s(\w{3})\s+(\d{1,2})\s(\d+:\d+)\s'
colors = ',reset,reset,reset,cyan'

[[rules]] # DateTime end
regexp = '\s-\s(\d+:\d+)'
colors = ',magenta'

[[rules]] # DateTime - down
regexp = '\s-\s(down)'
colors = ',red'

[[rules]] # DateTime - crash
regexp = '\s-\s(crash)'
colors = ',bold black bgred'

[[rules]] # still logged in
regexp = 'still logged in'
colors = ',bold black bgcyan'

[[rules]] # still running
regexp = '(still running)'
colors = ',green'

[[rules]] # Time
regexp = '\((\d+\+)?(\d+):(\d+)\)'
colors = ',red,yellow,green'

[[rules]] # pts
regexp = '\s(pts[\S]+)'
colors = ',green'

[[rules]] # tty
regexp = '\s(tty\d)'
colors = ',blue'

[[rules]] # reboot
regexp = '^(reboot\s+system boot)'
colors = ',red'

[[rules]] # Third column IP
regexp = '(?:\s|\()(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?:\s|\))'
colors = ',bold red'

[[rules]] # Third column local
regexp = '(?:\s|\()(\:0)(?:\s|\))'
colors = ',bold black cyan'
