"$schema" = "../rule.schema.json"

[[rules]] # Main
regexp = "(.*) '(.*)'"
colors = ',bold red,path'

[[rules]] # Directory
regexp = "(.*) (directory) '(.*)'"
colors = ',bold red,bold magenta,path'
overwrite = true
