"$schema" = "../rule.schema.json"

[[rules]] # Field
regexp = '(\S+):\s'
colors = 'cyan'

[[rules]] # Filename
regexp = 'File: ‘?(\S+)’?'
colors = 'bold magenta'

[[rules]] # File-Type
regexp = 'IO\s*Block:\s*\d+\s+(.*)$'
colors = 'bold green'

[[rules]] # Permission-Numbers
regexp = '\((\d)(\d)(\d)(\d)\/'
colors = 'bold white,green,yellow,red'

[[rules]] # owner-rwx
regexp = '(?:[-bcCdDlMnpPs?]((-|r)(-|w)(-|[xsStT]))(-|r)(-|w)(-|[xsStT])(-|r)(-|w)(-|[xsStT]))'
colors = 'bold green,bold red,bold yellow'
