"$schema" = ' "../rule.schema.json"'

[[rules]] # Number
regexp = '^\s*(\d+)\s+'
colors = 'bold white'

[[rules]] # hostname
regexp = '(\s\w+[\w\-\.]+\w+)'
colors = 'bold blue'

[[rules]] # IP
regexp = '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
colors = 'magenta'

[[rules]] # IPv6
regexp = '(([0-9a-fA-F]{1,4})?\:\:?[0-9a-fA-F]{1,4})+'
colors = 'magenta'

[[rules]] # Time
regexp = '(?:(\d+\.?\d*)\s*ms)'
colors = 'green'

[[rules]] # ms
regexp = '\b(ms)\b'
colors = 'yellow'

[[rules]] # DUP
regexp = '\b(DUP)'
colors = 'red'

[[rules]] # host_unreachable
regexp = '\s\!([HNPSFXVC]|\d+)'
colors = 'red'

[[rules]] # TTL
regexp = '(ttl=\d+\!)'
colors = 'cyan'

[[rules]] # star
regexp = '(\*)'
colors = 'red'

[[rules]] # parenthesis
regexp = '(\(|\))'
colors = 'yellow'
