"$schema" = ' "../rule.schema.json"'

[Number]
regexp = '^\s*(\d+)\s+'
colors = 'bold white'

[hostname]
regexp = '(\s\w+[\w\-\.]+\w+)'
colors = 'bold blue'

[IP]
regexp = '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
colors = 'magenta'

[IPv6]
regexp = '(([0-9a-fA-F]{1,4})?\:\:?[0-9a-fA-F]{1,4})+'
colors = 'magenta'

[Time]
regexp = '(?:(\d+\.?\d*)\s*ms)'
colors = 'green'

[ms]
regexp = '\b(ms)\b'
colors = 'yellow'

[DUP]
regexp = '\b(DUP)'
colors = 'red'

[host_unreachable]
regexp = '\s\!([HNPSFXVC]|\d+)'
colors = 'red'

[TTL]
regexp = '(ttl=\d+\!)'
colors = 'cyan'

[star]
regexp = '(\*)'
colors = 'red'

[parenthesis]
regexp = '(\(|\))'
colors = 'yellow'
