"$schema" = "../rule.schema.json"

[[rules]] # Title
regexp = '(procs)\s(-+memory-+)\s(-+swap-+)\s(-+io-+)\s(-+system-+)\s(-+cpu-+)'
colors = 'bold,bold cyan,bold magenta,bold blue, bold green, bold red'

[[rules]] # rows
regexp = '^(\s*\w+\s+\w+)\s+(\w+\s+\w+\s+\w+\s+\w+)\s+(\w+\s+\w+)\s+(\w+\s+\w+)\s+(\w+\s+\w+)\s+(\w+\s+\w+\s+\w+\s+\w+\s+\w+)'
colors = 'reset,cyan,magenta,blue,green,red'

#  ============================ DISK MODE =================================
[[rules]] # Title disk mode
regexp = '^(disk-)\s(-+reads-+)\s(-+writes-+)\s(-+IO-+)'
colors = 'bold,bold green,bold magenta,bold blue'

[[rules]] # Title disk mode
regexp = '(\s+)(total\s+merged\s+sectors\s+ms)\s+(total\s+merged\s+sectors\s+ms)\s+(cur\s+sec)'
colors = 'bold,bold green,bold magenta,bold blue'

[[rules]] # rows disk mode
regexp = '^(\S+)\s+(\d+\s+\d+\s+\d+\s+\d+)\s+(\d+\s+\d+\s+\d+\s+\d+)\s+(\d+\s+\d+)'
colors = 'white,green,magenta,blue'
