name: Release

on:
  push:
    tags: "v*"

jobs:
  release:
    name: Create the release
    runs-on: ubuntu-latest
    steps:
      - name: Clone the git repository
        uses: actions/checkout@main

      - name: Get Version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "major=${major}" >> $GITHUB_OUTPUT

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/*.sum"

      - name: Archive Builds
        run: |
          make VERSION=${{ steps.version.outputs.tag }} archive

      - name: Create release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "archive/*"
          tag: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          draft: true
